---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: '../../data_bags'

platforms:
  - name: freebsd-10.2
    driver:
      box: freebsd-10.2-chef
      network:
      - ["private_network", {ip: "192.168.33.39"}]
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[chef-freebsd-users::default]
      - recipe[chef-freebsd-users::vim]
    attributes:
