name 'chef-freebsd-users'
maintainer 'Steve King'
maintainer_email ''
license 'mit'
description 'Installs/Configures chef-freebsd-users'
long_description 'Installs/Configures chef-freebsd-users'
version '0.1.0'
